apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.backend.name }}-depl
    namespace: {{ .Release.namespace }}

spec:
    replicas: {{ .Values.backend.replicas }}
    selector:
        matchLabels:
            app: backend-app
    template:
        metadata:
            labels:
                app: backend-app
        spec:
            containers:
            -   name: backend
                image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
                resources:
                    limits:
                        cpu: "150m"
                        memory: "200Mi"
                readinessProbe:
                    httpGet:
                        path: /ready
                        port: 3500
                    initialDelaySeconds: 15
                    periodSeconds: 10
                ports:
                -   containerPort: 3500
                env:
                -   name: MONGO_CONN_STR
                    valueFrom:
                        secretKeyRef:
                            name: db-secrets
                            key: mongo-conn-str
                -   name: MONGO_USERNAME
                    valueFrom:
                        secretKeyRef:
                            name: db-secrets
                            key: mongo-username
                -   name: MONGO_PASSWORD
                    valueFrom:
                        secretKeyRef:
                            name: db-secrets
                            key: mongo-password