apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}-svc
  namespace: {{ .Release.namespace }}
spec:
    type: ClusterIP
    selector:
        app: backend-app
    ports:
    -   protocol: TCP
        port: 3500
        targetPort: 3500