apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.frontend.name }}-svc
    namespace: {{ .Release.namespace }} 
spec:
    type: ClusterIP
    selector:
        app: frontend-app
    ports:
    -   protocol: TCP  
        port: 80
        targetPort: 80